root = "."

[build]
  bin = "/usr/local/go/bin/go run cmd/console/main.go"
  cmd = "/home/bernardo/gopath/bin/gofumpt -e -l -w ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html", "toml", "env"]
  kill_delay = "0s"
  stop_on_error = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
