root = "."
tmp_dir = "tmp"

[build]
  pre_cmd = [
    "echo 'build.pre_cmd'",
    # "goimports -l -w -d ./..",
    "go mod tidy",
  ]
  cmd = "echo 'build.cmd' ; go build -o ~/tmp/bin_for_air cmd/console/main.go"
  post_cmd = ["echo 'build.post_cmd'"]

  full_bin = "echo 'build.full_bin' ; ~/tmp/bin_for_air"

  include_ext = ["go", "toml", "yaml", "yml", "env"]
  exclude_dir = ["vendor", "tmp", "dist", "service"]
  include_file = ["Makefile"]
  exclude_regex = ["_test\\.go", "\\.md", "\\.sample"]
  follow_symlink = true

  log = "tmp/air.log"
  stop_on_error = true
  send_interrupt = true
