root = "."

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main cmd/console/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  stop_on_error = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
